// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzeWdRmiWhiQKHo29UI9HtM6JAqTSRws4',
    appId: '1:910027714987:web:fc0b3ab9fa9be822f762ee',
    messagingSenderId: '910027714987',
    projectId: 'comet-hackathon-fe4f4',
    authDomain: 'comet-hackathon-fe4f4.firebaseapp.com',
    storageBucket: 'comet-hackathon-fe4f4.appspot.com',
    measurementId: 'G-361DKL8FDC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDw6VTv-EV_1Rr3ZybiliiFdWISNqo2DBc',
    appId: '1:910027714987:android:cacd34d6d34bf2c7f762ee',
    messagingSenderId: '910027714987',
    projectId: 'comet-hackathon-fe4f4',
    storageBucket: 'comet-hackathon-fe4f4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDZF-daigwwQO4augtQ9gnpSSdGDui6PtE',
    appId: '1:910027714987:ios:6c4161f06a899c29f762ee',
    messagingSenderId: '910027714987',
    projectId: 'comet-hackathon-fe4f4',
    storageBucket: 'comet-hackathon-fe4f4.appspot.com',
    iosClientId: '910027714987-l8q78mdkt131tm41ferbt66svbs43kci.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCometHackathon',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDZF-daigwwQO4augtQ9gnpSSdGDui6PtE',
    appId: '1:910027714987:ios:6c4161f06a899c29f762ee',
    messagingSenderId: '910027714987',
    projectId: 'comet-hackathon-fe4f4',
    storageBucket: 'comet-hackathon-fe4f4.appspot.com',
    iosClientId: '910027714987-l8q78mdkt131tm41ferbt66svbs43kci.apps.googleusercontent.com',
    iosBundleId: 'com.example.appCometHackathon',
  );
}
